name: Automated CI
on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.3' # The Go version to download (if necessary) and use.

      # build 시에 발생하는 캐시가 약 30초 정도 걸렸음. 캐시를 적용하면 시간이 크게 줄어든다.
      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/go/pkg/mod
            /home/runner/.cache/go-build
          key: go-build-cache-${{ hashFiles('go.sum') }}

      - name: Test and Build a binary
        run: |
          KHUMU_HOME=$(pwd) go test ./... -v
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bumblebee ./...
      - name: 🍦 Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 🏗️ Build images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false # buildkit을 쓰면 auto push가 안되는듯?
          tags: |
            umi0410/bumblebee:latest
            umi0410/bumblebee:${{ github.run_id }}
      - name: 🏗️ Push images
        run: |
          docker push umi0410/bumblebee:latest
          docker push umi0410/bumblebee:${{ github.run_id }}
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.8.6"

      - name: 🛎 Clone the devops repository
        uses: actions/checkout@v2
        with:
          repository: khu-dev/khumu-devops
          token: ${{ secrets.PUSH_TO_OTHER_REPO }}
          path: 'khumu-devops'

      - name: Edit Kustomization.yaml
        working-directory: khumu-devops/khumu-comment
        run: |
          kustomize version
          kustomize edit set image umi0410/bumblebee=umi0410/bumblebee:${{ github.run_id }}
      - name: Push to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_TO_OTHER_REPO }}
        with:
          source-directory: khumu-devops
          destination-github-username: 'khu-dev'
          destination-repository-name: 'khumu-devops'